<template>
  <div>
    <h5
      class="
        font-sans-condensed
        text-indigo-200
        tracking-wider
        text-[16px]
        uppercase
        md:text-[28px]
      "
    >
      <slot></slot>
    </h5>
  </div>
</template>
